### ISSUE TITLE
Toast

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/auro#21]
# Component Audit

The scope of this issue is to track the full progress of the [auro-toast](https://github.com/AlaskaAirlines/auro-toast) component.

## Process

This issue is to remain open until all areas of the specification and all assets have been delivered to stakeholders and user groups.

As new issues are created that are children of this Audit item, please be sure to reference this Audit item in that issue.

As assets are delivered, it is required that the labels associated with this Audit issue are updated to reflect status. Labels are as follows:

- Artwork
- Code
- Docs
- Ui Kit

This Audit issue will remain open until all assets have been delivered be it V0 or ADS compliment.

**Comment by znewton** [comment]
It could be an interesting value-add for HeaderFooter to have a public API that allows for the addition of a Toast to a queue. A use case could be using `window.hfApi.queueToast(severity, message, duration)` so that even if a page is navigated away from, their purchase confirmation still follows them for the defined duration.

**Comment by blackfalcon** [comment]
Design required re-evaluation as to use with the Auro design system. No designer assigned at this time.

**Comment by blackfalcon** [comment]
This is being descoped from priority status. Unable to move this forward this sprint.

**Comment by blackfalcon** [comment]
Work is in progress from @Izook

**Comment by blackfalcon** [comment]
Work assigned to @jason-capsule42
