### ISSUE TITLE
auro-badge: type label floats a bit too high in badge

### ISSUE THREAD

**Issue by erikalanghauser** [AlaskaAirlines/auro#223]
## Describe the bug
There is an issue with the line-height and padding that is causing the type to float too high in the badge and no longer match the design comps.

## To Reproduce
1. Go to https://auro.alaskaair.com/components/auro/badge
2. Look at label option
3. Type is floating high.
4. Compare to screenshots below of comp vs code.

## Expected behavior
Ideally, the browser doesn't move the height to compensate for ascenders/descenders. Possibility to make this a config option.

## Screenshots
Left: design comp; Right: code
![image](https://user-images.githubusercontent.com/34354487/106680629-c246db00-6573-11eb-9469-58208184b558.png)
![image](https://user-images.githubusercontent.com/34354487/106680641-c70b8f00-6573-11eb-9b4f-6ae466a5d61b.png)

## Additional context
For our usage of the auro-badge label as the layover length, the format will always be "0h 0m" so there will never be any ascenders/descenders in the label field.

**Comment by jason-capsule42** [comment]
I met with Scott Shepherd today to discuss options (Erika is OOF). We believe we understand the intent of what Erika is asking for. However, vertically centering the text for one content string can look unaligned for another.

For instance "PPPPP" vs "ppppp". Centering the content for the uppercase string would result in the lowercase string appearing to be too low in the badge. On the other hand "Ppppp" would generally fill centered since there is at least one uppercase character.

Scott believes it is unlikely we would see the implementation of a badge that does not include at least one uppercase character. Therefor, centering all content such that any string with 1 or more uppercase characters and no descenders are always vertically centered would achieve the intended goal.
